### ISSUE TITLE
Milestone 1 - Final product

### ISSUE THREAD

**Issue by berkethetechnerd** [berkethetechnerd/ALPS-DeviceTracking#14]
Hurray! We are at the end of the first milestone.
What we need to finalize it,

- [x] Test the UI functionality of the application. Think about the edge corners, solve bugs if there are any.
- [x] Create and present an APK file. 
- [x] Release the APK file on Github.
